### ISSUE TITLE
Questions on selectable priorities support in select.cpp

### ISSUE THREAD

**Issue by sunnogo** [Azure/sonic-swss-common#210]
* It seems epoll do not sort events by fd. How to guarantee we can handle events of high priority seletable first?

```
        ret = ::epoll_wait(m_epoll_fd, events.data(), sz_selectables, timeout);
```

*  It seems that we need to update updateLastUsedTime in all used seletables? Why not update them in the for block? And it seems that only update the first item in set m_ready in the if block. 

```
int Select::poll_descriptors(Selectable **c, unsigned int timeout)
{
    int sz_selectables = static_cast<int>(m_objects.size());
    std::vector<struct epoll_event> events(sz_selectables);
    int ret;

    do
    {
        ret = ::epoll_wait(m_epoll_fd, events.data(), sz_selectables, timeout);
    }
    while(ret == -1 && errno == EINTR); // Retry the select if the process was interrupted by a signal

    if (ret < 0)
        return Select::ERROR;

    for (int i = 0; i < ret; ++i)
    {
        int fd = events[i].data.fd;
        Selectable* sel = m_objects[fd];
        sel->readData();
        m_ready.insert(sel);  <---- why not update updateLastUsedTime here?
    }

    if (!m_ready.empty())
    {
        auto sel = *m_ready.begin();  <---- only update the first item

        *c = sel;

        m_ready.erase(sel);
        // we must update clock only when the selector out of the m_ready
        // otherwise we break invariant of the m_ready
        sel->updateLastUsedTime();

        if (sel->hasCachedData())
        {
            // reinsert Selectable back to the m_ready set, when there're more messages in the cache
            m_ready.insert(sel);
        }

        sel->updateAfterRead();

        return Select::OBJECT;
    }

    return Select::TIMEOUT;
}
```

**Comment by pavel-shirshov** [comment]
> It seems epoll do not sort events by fd. How to guarantee we can handle events of high priority seletable first?

When we receive events from epoll we insert them into m_ready queue. The m_ready queue is a set (rb tree inside), which is ordered by Select::cmp object. This object defines order by Pri and LastUsedTime.
The m_ready iterator always gives us objects in a sorted way.

> It seems that we need to update updateLastUsedTime in all used seletables? Why not update them in the for block? And it seems that only update the first item in set m_ready in the if block.
LastUsedTime it's a property which define when last time the object was returned from poll_descriptors.
We need this to make priority inside of one Pri class, othewise if we have two selectables with the same Pri, the one could monopolize a queue by itself. In my code we make sure that we have a fair queue inside of one Pri class.

I update only first item because I need only first item. We return it, so we use it, so we update LastUsedTime property.
